image: Visual Studio 2019

# Version format
version: 5.0.0.{build}

branches:
  only:
    - develop
    - master   

platform: Any CPU

configuration: Release

build_script: 
  - ps: .\Packaging\BuildPackage.ps1 beta-$(APPVEYOR_BUILD_VERSION)

artifacts:
  - path: dist\*.nupkg
  - path: dist\*.zip
  


deploy:
 # MyGet Deployment for beta releases  
  - provider: NuGet
    server: https://www.myget.org/F/dawoe-umbraco/api/v2/package
    api_key:
      secure: xuhyqGpLpjeK0tUansB6IVWy89Fw+yqGqCmCpVuAY1fnDjfYrxA/gVGNBh8oU0JA
    artifact: /.*\.nupkg/
    on:
      branch: develop
      
 # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: 2NNEN9lVF0/cA40PZrm64BMMK34Y26A8xK22eUdWcN/7Nn5KyyRH2+THumy91tcV
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

# NuGet Deployment for releases
  - provider: NuGet
    server:
    api_key:
      secure: f5ijMJdo8hygOHm+RRD4pCBcRqj6uw4AWqDgG4MvA1x5sgdmcuRxvdtN1Cn2NB6I
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true

